### ISSUE TITLE
Black images when sampling from MNIST ?

### ISSUE THREAD

**Issue by jucor** [rosejn/torch-datasets#12]
Hi Jeff!  
@andreirusu suggested that we open an issue. @DaniloCylib gets some fully black images when he samples from the MNIST dataset:
![Screen Shot 2012-12-14 at 14 54 39](https://f.cloud.github.com/assets/660037/19175/d6d0f0b0-4902-11e2-898d-041a6e44d847.png)

We will attach a code snipppet shortly, possibly with a set random seed allowing for reproduction. It could be the way we do the minibatch-subsampling, I'm not sure.
Cheers,

**Comment by rosejn** [comment]
Hi,
  If you can send me the two calls you make to create the data set and make
the sampler that should be enough to track it down.

Jeff

**Comment by DaniloRezende** [comment]
I'll send you a file asap.

**Comment by rosejn** [comment]
You can just paste those two lines here.

**Comment by DaniloRezende** [comment]
data = Mnist.dataset() -- non scaled MNIST    

-- Extract a Tensor of minibatch from 'dataset' package
local function getRandomMiniBatch(data, nObs)

   local nSamples = data.dataset.data:size(1) -- total number of samples
   local dim = data.dataset.data[1]:nElement() --dimension

   local batch = torch.Tensor(nObs, dim)

   for i = 1,nObs do
      local j = torch.random()%nSamples+1 --sample locally
      batch[i]:copy( data.dataset.data[j]:resize(dim) )
   end

   return batch
end

local dataMatrix = getRandomMiniBatch(data, 100) 

--[[
if we display the rows of this tensor as images, we'll find the black samples.   I have not checked the explicit values of the pixels though.
--]]

**Comment by jucor** [comment]
That does not seem to be enough: I tried below, and don't have any black images displayed.

``` lua
require 'dataset/mnist'
require 'torch'
require 'image'


-- Extract a Tensor of minibatch from 'dataset' package
local function getRandomMiniBatch(data, nObs)

   local nSamples = data.dataset.data:size(1) -- total number of samples
   local dim = data.dataset.data[1]:nElement() --dimension

   local batch = torch.Tensor(nObs, dim)

   for i = 1,nObs do
   local j = torch.random()%nSamples+1 --sample locally
      batch[i]:copy( data.dataset.data[j]:resize(dim) )
   end

   return batch
end

data = Mnist.dataset() -- non scaled MNIST
for s=1,100 do
   print('seed:', s)
   torch.manualSeed(s)
   local dataMatrix = getRandomMiniBatch(data, 100)
   image.display{image=dataMatrix:resize(100, 28, 28), nrow=10}
end
```

**Comment by DaniloRezende** [comment]
solved.   This issue disappeared when I pulled the newest torch-dataset.

**Comment by rosejn** [comment]
Ahh, good.  Checkout the new readme too, because I added a few of the features you guys wanted.
