### ISSUE TITLE
wrong labels to the visualized pixels of mnist.t7

### ISSUE THREAD

**Issue by nejyeah** [rosejn/torch-datasets#30]
I load the mnist.t7/train_32x32.t7 , then I use gfx to show the first 10 images in train .
The show are:                5 0 4 1  9  2 1 3 1 4
but trainData.labels are: 6 1 5 2 10 3 2 4 2 5
So does the test_32x32.t7 .  Is anybody have try?

**Comment by akfidjeland** [comment]
The labels are 1-based since all of indexing in lua and torch is 1-based, so images of the number '0' have label 1, '1' has label 2, etc.
