### ISSUE TITLE
Having problem installing the package

### ISSUE THREAD

**Issue by haanvid** [rosejn/torch-datasets#32]
I want to use 'torch-datasets ' to load weizmann dataset but there is no 'torch-datset '

by using the following functions

require 'dataset/videoset'
 d = VideoSet.dataset({dir='KTH'})
 while true do w=image.display({image=d().data,win=w}) util.sleep(1/10) end

torch.save(filename, object [, format])

So,

I tried

' luarocks install [package] ' command but it didn't work.
So I tried putting the 'datasets' file in the ~/torch/install/share/lua/5.1 folder, but it didn't work

Then I found out that there was a CmakeList.txt  and tried to install using the txt, but
could not find how to do it.

Can somebody please tell me how to install this package?

**Comment by almson** [comment]
I would like clarification on this as well. I receive the following error:

```
[string "require('dataset/mnist')..."]:1: loop or previous error loading module 'dataset/mnist' stack traceback
[C]: in function 'require'
[string "require('dataset/mnist')..."]:1: in main chunk
[C]: in function 'xpcall'
/home/alex/torch/install/share/lua/5.1/itorch/main.lua:177: in function </home/alex/torch/install/share/lua/5.1/itorch/main.lua:143>
/home/alex/torch/install/share/lua/5.1/lzmq/poller.lua:75: in function 'poll'
/home/alex/torch/install/share/lua/5.1/lzmq/impl/loop.lua:307: in function 'poll'
/home/alex/torch/install/share/lua/5.1/lzmq/impl/loop.lua:325: in function 'sleep_ex'
/home/alex/torch/install/share/lua/5.1/lzmq/impl/loop.lua:370: in function 'start'
/home/alex/torch/install/share/lua/5.1/itorch/main.lua:344: in main chunk
[C]: in function 'require'
[string "arg={'/home/alex/.ipython/profile_torch/secur..."]:1: in main chunk
```

**Comment by cagbal** [comment]
I have the same issue, luarocks does not work and there is no pre-installed package in torch.

**Comment by Macrosmatic** [comment]
There is a folder named "dataset" inside the torch-datasets project. I believe you should put this folder with your file, and the include should work fine.

I am having a different problem, which I believe you may also have to face later. Inside "dataset" there is a file "SimpleDataset.lua" which requires "dataset" (plain "dataset", no subfile); obviously there is no file .lua named so, and an error is raised.

About the CMakeList, I believe you should use it with cmake ("cmake CMakeList.txt", it will create a Makefile), the installation completed, but it did nothing for me.

**Comment by Macrosmatic** [comment]
Update:
I could successfully import dataset by copying the "dataset" folder to ~/torch/install/share/lua/5.1/
There seems to be a bug in the cmake/make process. I don't believe I was supposed to do that manually.
